[build]
  command = "cd portfolio-react && npm install --legacy-peer-deps && npm run build"
  publish = "portfolio-react/dist"

[functions]
  directory = "portfolio-react/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
