[build]
  command = "cd portfolio-react && npm install --legacy-peer-deps && npm run build"
  publish = "portfolio-react/dist"

[build.environment]
  NODE_VERSION = "22"

[functions]
  directory = "portfolio-react/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/og-image.png"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    Content-Type = "image/png"

[[headers]]
  for = "/favicon*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400, immutable"

[[headers]]
  for = "/apple-touch-icon.png"
  [headers.values]
    Cache-Control = "public, max-age=86400, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
